### ISSUE TITLE
Convert `OR` with the list of prefix/suffix/regex matches into `rlike` + regexes concatenation

### ISSUE THREAD

**Issue by alexott** [alexott/pySigma-backend-databricks#12]
Some rules could be optimized by converting repeated `OR` operations + `contains` or `endswith` into corresponding regexes.

Instead of `rlike lower('...')` we can generate `rlike '(?i)....'`.

## Example 1: contains

I.e., expression from `./rules/macos/process_creation/proc_creation_macos_security_software_discovery.yml`

```yaml
detection:
    image:
        Image: '/usr/bin/grep'
    selection_cli_1:
        CommandLine|contains:
            - 'nessusd'        # nessus vulnerability scanner
            - 'santad'         # google santa
            - 'CbDefense'      # carbon black
            - 'falcond'        # crowdstrike falcon
            - 'td-agent'       # fluentd log shipper
            - 'packetbeat'     # elastic network logger/shipper
            - 'filebeat'       # elastic log file shipper
            - 'auditbeat'      # elastic auditing agent/log shipper
            - 'osqueryd'       # facebook osquery
            - 'BlockBlock'     # Objective-See persistence locations watcher/blocker
            - 'LuLu'           # Objective-See firewall management utility
    selection_cli_2: # Objective Development Software firewall management utility
        CommandLine|contains|all:
            - 'Little'
            - 'Snitch'
    condition: image and 1 of selection_cli_*
```

Is now converted into 

```yaml
- name: Security Software Discovery - MacOs
  severity: 30
  sql: lower(image) = lower('/usr/bin/grep') AND (contains(lower(command_line), lower('nessusd'))
    OR contains(lower(command_line), lower('santad')) OR contains(lower(command_line),
    lower('CbDefense')) OR contains(lower(command_line), lower('falcond')) OR contains(lower(command_line),
    lower('td-agent')) OR contains(lower(command_line), lower('packetbeat')) OR contains(lower(command_line),
    lower('filebeat')) OR contains(lower(command_line), lower('auditbeat')) OR contains(lower(command_line),
    lower('osqueryd')) OR contains(lower(command_line), lower('BlockBlock')) OR contains(lower(command_line),
    lower('LuLu')) OR contains(lower(command_line), lower('Little')) AND contains(lower(command_line),
    lower('Snitch')))
```

Could be represented as:

```yaml
- name: Security Software Discovery - MacOs
  severity: 30
  sql: lower('/usr/bin/grep') AND (lower(command_line)  rlike lower('.*(nessusd|santad|CbDefense|falcond|td-agent|packetbeat|filebeat|auditbeat|osqueryd|BlockBlock|LuLu).*') OR contains(lower(command_line), lower('Little')) AND contains(lower(command_line), lower('Snitch')))
```

## Example 2: endswith

This rule:

```yaml
detection:
    selection:
        Image|endswith:
            - '/shutdown'
            - '/reboot'
            - '/halt'
    condition: selection
```

is now converted into the following code:

```yaml
- name: System Shutdown/Reboot - MacOs
  sql: endswith(lower(image), lower('/shutdown')) OR endswith(lower(image), lower('/reboot'))
    OR endswith(lower(image), lower('/halt'))
```

But it could be represented as:

```
- name: System Shutdown/Reboot - MacOs
  sql: lower(image) rlike lower('.*(/shutdown|/reboot|/halt)')
```

## Example 3: startswith

This rule:

```yaml
detection:
    selection:
        c-useragent|startswith:
        # XMRig
            - 'XMRig '
        # CCMiner
            - 'ccminer'
    condition: selection
```

is now converted into 

```yaml
- name: Crypto Miner User Agent
  severity: 50
  sql: startswith(lower(c_useragent), lower('XMRig ')) OR startswith(lower(c_useragent),
    lower('ccminer'))
```

but it could be represented as the following:

```yaml
- name: Crypto Miner User Agent
  severity: 50
  sql: lower(c_useragent) rlike lower('(XMRig |ccminer).*')
```

## Example 4:

When there is a combination of `contains`, `startswith` or `endswith`, we need to generate separate `rlike` expressions for each operator.
